export const DATA = [
  {
    id: 1,
    imgUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2018/11/Skin-cancer-press-release-28-11-18-cropped.jpg",
    title:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    theme: "blue",
    url: "/go-to-url",
    name: "Dr Tanya Bleiker",
    about:
      "President in The Chair July 2020 - July 2022 University Hospitals of Derby and Burton",
    profileUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2018/12/Image_62_Text__Image.jpg",
  },
  {
    id: 2,
    imgUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2021/04/Copy-of-SAW-1-Twitter.png",
    title:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    theme: "yellow",
    url: "/go-to-url",
    name: "Dr Mabs Chowdhury",
    about:
      "President in The Chair July 2020 - July 2022 University Hospitals of Derby and Burton",
    profileUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2018/12/Image_62_Text__Image.jpg",
    cardTitle: "This is a tile",
  },
  {
    id: 3,
    imgUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2020/12/pexels-polina-tankilevitch-3735747-scaled-e1607434622754.jpg",
    title:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    theme: "danger",
    url: "/go-to-url",
    name: "Professor Richard Warren",
    about:
      "President in The Chair July 2020 - July 2022 University Hospitals of Derby and Burton",
    profileUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2018/12/Image_62_Text__Image.jpg",
    cardTitle: "This is a tile",
  },
  {
    id: 4,
    imgUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2020/12/pexels-polina-tankilevitch-3735747-scaled-e1607434622754.jpg",
    title:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    theme: "danger",
    url: "/go-to-url",
    name: "Professor Richard Warren",
    about:
      "President in The Chair July 2020 - July 2022 University Hospitals of Derby and Burton",
    profileUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2018/12/Image_62_Text__Image.jpg",
    cardTitle: "This is a tile",
  },
];

export const MENU_DATA = [
  {
    title: "Patient Information Leaflets",
    url: "/patient-information-leaflets/",
  },
  {
    title: "BAD Affiliated Groups",
    url: "/derm-groups-charity/",
  },
  {
    title: "Patient Hub",
    url: "https://www.skinhealthinfo.org.uk/",
  },
  {
    title: "COVID 19 Information",
    url: "/covid-19/",
  },
  {
    title: "CED Journal",
    url: "/research-journals/journals/clinical-and-experimental-dermatology/",
  },
  {
    title: "BJD Journal",
    url: "/research-journals/journals/british-journal-of-dermatology/",
  },
  {
    title: "SHD Journal",
    url: " /research-journals/journals/skin-health-and-disease/",
  },
  {
    title: "Clinical Guidelines",
    url: "/guidelines-and-standards/clinical-guidelines/",
  },
];

export const ALPHABET = [
  "0-9",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];

export const UK_COUNTIES = [
  "Avon",
  "Bedfordshire",
  "Berkshire",
  "Buckinghamshire",
  "Cambridgeshire",
  "Cheshire",
  "Cleveland",
  "Cornwall",
  "Cumbria",
  "Derbyshire",
  "Devon",
  "Dorset",
  "Durham",
  "East Sussex",
  "Essex",
  "Gloucestershire",
  "Hampshire",
  "Herefordshire",
  "Hertfordshire",
  "Isle of Wight",
  "Kent",
  "Lancashire",
  "Leicestershire",
  "Lincolnshire",
  "London",
  "Merseyside",
  "Middlesex",
  "Norfolk",
  "Northamptonshire",
  "Northumberland",
  "North Humberside",
  "North Yorkshire",
  "Nottinghamshire",
  "Oxfordshire",
  "Rutland",
  "Shropshire",
  "Somerset",
  "South Humberside",
  "South Yorkshire",
  "Staffordshire",
  "Suffolk",
  "Surrey",
  "Tyne and Wear",
  "Warwickshire",
  "West Midlands",
  "West Sussex",
  "West Yorkshire",
  "Wiltshire",
  "Worcestershire",
  "Clwyd",
  "Dyfed",
  "Gwent",
  "Gwynedd",
  "Mid Glamorgan",
  "Powys",
  "South Glamorgan",
  "West Glamorgan",
  "Aberdeenshire",
  "Angus",
  "Argyll",
  "Ayrshire",
  "Banffshire",
  "Berwickshire",
  "Bute",
  "Caithness",
  "Clackmannanshire",
  "Dumfriesshire",
  "Dunbartonshire",
  "East Lothian",
  "Fife",
  "Inverness-shire",
  "Kincardineshire",
  "Kinross-shire",
  "Kirkcudbrightshire",
  "Lanarkshire",
  "Midlothian",
  "Moray",
  "Nairnshire",
  "Orkney",
  "Peeblesshire",
  "Perthshire",
  "Renfrewshire",
  "Ross-shire",
  "Roxburghshire",
  "Selkirkshire",
  "Shetland",
  "Stirlingshire",
  "Sutherland",
  "West Lothian",
  "Wigtownshire",
  "Antrim",
  "Armagh",
  "Down",
  "Fermanagh",
  "Londonderry",
  "Tyrone",
];

export const UK_COUNTRIES = [
  "England",
  "Wales",
  "Scotland",
  "Northern Ireland",
];

export const UK_HOSPITALS = [
  "Not in list",
  "48th Medical Group",
  "9A Wilbraham Place",
  "Aberdeen Royal Infirmary",
  "About Health Community Dermatology Service",
  "Addenbrooke's Hospital",
  "Aintree University Hospital",
  "Alder Hey Childrens Hospital",
  "Alexandra Hospital",
  "All India Institute Of Medical Sciences",
  "Altnagelvin Area Hospital",
  "American Hospital Dubai",
  "Amersham Hospital",
  "Antrim Area Hospital",
  "Aorangi Consulting Rooms",
  "Arrowe Park Hospital",
  "As'Ad Al-Hamad Dermatology Center",
  "Ashford Hospital",
  "Ashtead Hospital",
  "Auckland District Health Board",
  "Barnet General Hospital",
  "Barnsley District Gen Hospital",
  "Barts & The London School of Medicine and Dentistry",
  "Basildon University Hospital",
  "Basingstoke & North Hampshire Hospital",
  "Bassetlaw District General Hospital",
  "Baylor University Medical Center",
  "Baylor University Medical Centre",
  "Bayside Dermatology",
  "Beacon Consultants Clinic",
  "Beaumont Hospital",
  "Beckenham Beacon Hospital",
  "Bedford Hospital",
  "Belfast City Hospital",
  "Belgravia Dermatology Limited",
  "Birmingham Children's Hospital",
  "Birmingham City Hospital",
  "Blackrock Clinic",
  "BMI Carrick Glen Hospital",
  "BMI The Chaucer Hospital",
  "Bombay Leprosy Projt",
  "Bon Secours Hospital",
  "Bon Secours Hospital Dublin",
  "Borders General Hospital",
  "Borough Green Medical Practice",
  "Bowman Gray School of Medicine",
  "Brighton & Sussex University Hospitals NHS Trust",
  "Brighton General Hospital",
  "Bristol Royal Hospital for Children",
  "Bristol Royal Infirmary",
  "Broadgreen Hospital",
  "Broomfield Hospital",
  "Brough And South Cave Surgery",
  "Bunny Hill Primary Care Centre",
  "Bupa Health and Dental Care- Solihull",
  "Burnley General Hospital",
  "Cadogan Clinic",
  "Cairns Base Hospital",
  "Calderdale Royal Hospital",
  "Cambridge University Hospitals NHS Trust",
  "Cannock Chase Hospital",
  "Cardiff University School of Medicine",
  "Castellani Research Institute",
  "Castle Hill Hospital",
  "Causeway Hospital",
  "Cellite Clinic Ltd",
  "Central Middlesex Hospital",
  "Centre for Cutaneous Research",
  "Centre for Inflammation Research, The Queens Medical Research Institute",
  "Centre Hospitalier Universitaire Sart Tilman",
  "Centre Medical Sery",
  "Chang Gung Memorial Hospital",
  "Changi General Hospital",
  "Chapel Allerton Hospital",
  "Charing Cross Hospital",
  "Charite Hospital",
  "Chase Farm Hospital",
  "Chelsea & Westminster Hospital",
  "Chelsfield Park Hospital",
  "Cheltenham General Hospital",
  "Chesterfield Royal Hospital",
  "Children's University Hospital",
  "Chonnam University Medical School",
  "Chorley And South Ribble Hospital",
  "Christchurch Hospital",
  "Churchill Hospital",
  "City Hospital Dubai",
  "Civil Hospital",
  "Clatterbridge Hospital",
  "Clifton Hospital",
  "Colchester General Hospital",
  "Conquest Hospital",
  "Constable County Medical Centre",
  "Corbett Hospital",
  "Countess of Chester Hospital",
  "County Hospital",
  "Craigavon Area Hospital",
  "Crawley Hospital",
  "Crosshouse Hospital",
  "Croydon University Hospital",
  "Cumberland Infirmary",
  "Daisy Hill Hospital",
  "Darlington Primary Care Center",
  "Deddington Health Centre",
  "Delhi Dermatology Group",
  "Dermatologische Klinik und Poliklinik",
  "Dermatology Centre Parmova",
  "Dermatology Clinic",
  "Dermatology Team",
  "Dermatology Unit",
  "Derriford Hospital",
  "Devonshire Road Hospital",
  "Dewsbury and District Hospital",
  "Dodson House Clinic",
  "Doncaster Royal Infirmary",
  "Dorset County Hospital",
  "Dudley Group of Hospitals NHS Trust",
  "Dumfries & Galloway Royal Infirmary",
  "Ealing Hospital",
  "East Kent Hospitals University NHS Foundation Trust",
  "East Surrey Hospital",
  "Eastbourne District General Hospital",
  "Eastham Group Practice",
  "Epsom General Hospital",
  "Epworth Hospital",
  "Essex County Hospital",
  "Eudelo Dermatology & Skin Wellbeing",
  "Faculty Hospital Brno",
  "Family Surgery",
  "Forth Valley Royal Hospital",
  "Frimley Park Hospital",
  "Frimley Park NHS Foundation Trust",
  "Galway Clinic",
  "General Hospital (St Helier)",
  "Gentofte Hospital",
  "George Eliot Hospital",
  "Glan Clwyd Hospital",
  "Glasgow Caledonian University",
  "Glasgow Royal Infirmary",
  "Gleneagles Medical Centre",
  "Glenferrie Dermatology",
  "Gloucestershire Royal Hospital",
  "Good Hope Hospital",
  "Great Ormond Street Hospital for Children",
  "Greater Glasgow and Clyde NHS Board",
  "Greenlane Clinical Centre",
  "Groote Schuur Hospital",
  "Guy's & St Thomas' NHS Foundation Trust",
  "Guy's Hospital",
  "Hammersmith Hospital",
  "Harefield Hospital",
  "Harrogate District Hospital",
  "Health Services at Wolves",
  "Heart of England NHS Foundation Trust",
  "Heart of Hounslow Centre for Health",
  "Heartlands Hospital",
  "Hemel Hempstead Hospital",
  "Hereford County Hospital",
  "Hertford County Hospital",
  "Hillingdon Hospital",
  "Hinchingbrooke Hospital",
  "Hinckley And District Hospital",
  "Homerton University Hospital",
  "Hong Kong Dermatology Centre",
  "Hopital L'Archet BP079",
  "Horton Hospital",
  "Hospital Medica Sur Torre I-221",
  "Hospital of Brno-Bohunice",
  "Hospital Of St John & St Elizabeth",
  "Hospital of the University of Pennsylvania",
  "Hospital Universitario 'Virgen Macarena'",
  "Huddersfield Royal Infirmary",
  "Hull Royal Infirmary",
  "Imperial College London",
  "Institute of Dermatology",
  "Instituto Umbert Dermatologia",
  "International Foundation For Dermatology",
  "Ipswich Hospital",
  "İskenderun Gelişim Hospital-Department of Dermatology",
  "Iwade Health Centre",
  "James Paget University Hospital",
  "John Hopkins Aramco Healthcare",
  "John Radcliffe Hospital",
  "Juntendo University School of Medicine",
  "Jyujyo Rehabilitation Hospital",
  "Kasr Al Aini University Hospital",
  "Kent & Canterbury Hospital",
  "Kent & Canterbury Hospital",
  "Kettering General Hospital",
  "Khartouom General Hospital",
  "Kidderminster Hospital",
  "King Edward VII Hospital",
  "King George Hospital",
  "King's College Hospital",
  "King's College Hospital - Beckenham Beacon",
  "King's College London",
  "King's Mill Hospital",
  "Kingston Hospital",
  "Klinica Dermatologiczna",
  "Klinikum der Christian-Albrechts-Universitate zu Kiel",
  "Klinikum Stuttgart",
  "Knightsbridge Doctors",
  "Korle Bu Hospital",
  "Kyneton Medical Centre",
  "Lamberhurst Surgery",
  "Lancaster Medical School",
  "Lauriston Building",
  "Leeds Teaching Hospitals NHS Trust",
  "Leicester Royal Infirmary",
  "Leigh Infirmary",
  "Leighton Hospital",
  "Lewisham Hospital",
  "Lincoln County Hospital",
  "Lister Hopital",
  "Lister Hospital",
  "Liverpool John Moores University",
  "Liverpool School of Tropical Medicine",
  "London Dermatology Centre",
  "London Road Community Hospital",
  "London School of Hygiene & Trop Medicine",
  "Ludwig Maximillans University Munchen",
  "Luton & Dunstable Hospital",
  "Macclesfield District General Hospital",
  "Manchester Royal Infirmary",
  "Market Harborough Medical Centre",
  "Marselisborg Hospital",
  "Massachusetts General Hospital",
  "Mater Misericordiae Hospital",
  "Mater Private Hospital",
  "Mayo Clinic",
  "Mayo Clinic",
  "Mayo Clinic Arizona",
  "Medway Hospital",
  "Middlemore Hospital",
  "Midland Regional Hospital at Tullamore",
  "Midland Regional Hospital Mullingar",
  "Midwestern Regional Hospital",
  "Milton Keynes General Hospital",
  "Ministry of Health",
  "MM Institute of Medical Sciences & Research",
  "Monklands Hospital",
  "Montreal General Hospital",
  "Moxley Medical Centre",
  "MSD Sharp & Dohme GmbH",
  "Musgrove Park Hospital",
  "Mu'tah University Karak",
  "National Hospital In Kamechli",
  "National Institutes of Health",
  "Neaman Practice",
  "Neath Port Talbot Hospital",
  "New Cross Hospital",
  "New Royal Infirmary",
  "Newcastle University Medical School",
  "Newton Hospital",
  "NHS Lothian (Lauriston Building)",
  "Niat Special Dermatology Clinic",
  "Ninewells Hospital & Medical School",
  "Norfolk & Norwich University Hospital",
  "North Bristol NHS Trust",
  "North Devon District Hospital",
  "North Lincolnshire Community Dermatology Service",
  "North Middlesex Hospital",
  "North Middlesex University Hospital NHS Trust",
  "Northampton General Hospital",
  "Northern General Hospital",
  "Northwick Park & St Marks Hospitals",
  "Not Listed",
  "Nottingham University Hospitals NHS Trust",
  "Nr Khalidi Hospital",
  "Nuffield Health Taunton Hospital",
  "Obafemi Awolowo University",
  "Offices R&D",
  "Old Mill Surgery",
  "Oldchurch Hospital",
  "Ormskirk District General Hospital",
  "Orpington Hospital",
  "Osaka University",
  "Our Lady Of Lourdes",
  "Our Lady's Children's Hospital",
  "Owen Sound General & Marine Hospital",
  "Parkside Hospital",
  "Peninsula Medical School",
  "Peninsula Medical School (undergraduate)",
  "Perth Royal Infirmary",
  "Peterborough City Hospital",
  "Pilgrim Hospital",
  "Pinderfields General Hospital",
  "Pontefract General Infirmary",
  "Poole General Hospital",
  "Poole Hospital NHS Foundation Trust",
  "Portsmouth Hospitals NHS Trust",
  "Portuguese Institute of Oncology",
  "Postgraduate Institute for Medical Education & Research",
  "Preston Hall Hospital",
  "Prince Charles Hospital",
  "Prince Philip Hospital",
  "Princess Alexandra Hospital",
  "Princess Elizabeth Hospital",
  "Princess of Wales Hospital",
  "Princess Royal Hospital",
  "Princess Royal University Hospital",
  "Queen Alexandra Hospital",
  "Queen Elizabeth Hospital",
  "Queen Elizabeth Hospital",
  "Queen Elizabeth Hospital",
  "Queen Elizabeth Hospital",
  "Queen Elizabeth The Queen Mother Hospital",
  "Queen Elizabeth University Hospital",
  "Queen Margaret Hospital",
  "Queen Mary University Of London Blizard Building",
  "Queen Mary's School of Medicine and Dentistry",
  "Queen Mary's University Hospital",
  "Queen's Hospital",
  "Queens Hospital Burton",
  "Queen's Medical Centre",
  "Raigmore Hospital",
  "Rotherham District General Hospital",
  "Royal Alexandra Hospital",
  "Royal Berkshire Hospital",
  "Royal Blackburn Hospital",
  "Royal Bolton Hospital",
  "Royal Bournemouth Hospital",
  "Royal Brisbane and Women's Hospital",
  "Royal Cornwall Hospital",
  "Royal Darwin Hospital",
  "Royal Derby Hospital",
  "Royal Devon & Exeter Hospital",
  "Royal Free Hospital",
  "Royal Glamorgan Hospital",
  "Royal Gwent Hospital",
  "Royal Hallamshire Hospital",
  "Royal Hampshire County Hospital",
  "Royal Hospital for Children",
  "Royal Lancaster Infirmary",
  "Royal Liverpool & Broadgreen University Hospitals NHS Trust",
  "Royal Liverpool University Hospital",
  "Royal London Hospital",
  "Royal Marsden Hospital",
  "Royal Melbourne Hospital",
  "Royal North Shore Hospital",
  "Royal Preston Hospital",
  "Royal Shrewsbury Hospital",
  "Royal South Hants Hospital",
  "Royal Stoke University Hospital",
  "Royal Surrey County Hospital",
  "Royal Sussex County Hospital",
  "Royal United Hospital",
  "Royal United Hospital Bath NHS Trust",
  "Royal University Hospital",
  "Royal Victoria Hospital",
  "Royal Victoria Infirmary",
  "Ruhr-University Bochum",
  "Russells Hall Hospital",
  "Salford Royal NHS Foundation Hospital",
  "Salford Royal NHS Foundation Trust",
  "Salisbury District Hospital",
  "Sandwell General Hospital",
  "School of Pharmacy and Biomedical Sciences",
  "Scunthorpe General Hospital",
  "Selly Oak Hospital",
  "Service De Dermatologie",
  "Sheffield Children's Hospital",
  "Sheffield Teaching Hospitals NHS Foundation Trust",
  "Shropshire Skin Clinic",
  "Singapore General Hospital",
  "Singleton Hospital",
  "Sir Charles Gairdner Hospital",
  "Sir Paul Boffa Hospital",
  "Sitaram Bhartia Institute for Science & Research",
  "Skane University Hospital",
  "Skin & Cancer Foundation Australia",
  "Skin Centre",
  "Skin Clinic Erbach",
  "Sligo General Hospital",
  "Solihull Hospital",
  "South Coast Dermatology",
  "South Infirmary Victoria Hospital",
  "South Tyneside Distric Hospital",
  "Southampton General Hospital",
  "Southend Hospital",
  "Southlands Hospital",
  "Southmead Hospital",
  "Southport & Formby District Gen Hospital",
  "Speedwell Practice",
  "Spire Dunedin Hospital",
  "Spire Hospital Cardiff",
  "Spire Hospital Hesslewood",
  "Spire Hull & East Riding Hospital",
  "St Albans City Hospital",
  "St Cross Hospital",
  "St George Hospital",
  "St George's Hospital",
  "St Helen's & Knowsley NHS Trust",
  "St Helens Hospital",
  "St Helen's Hospital",
  "St Helier's Hospital",
  "St James' Hospital",
  "St James's University Hospital",
  "St Luke's Hospital",
  "St Mary's Hospital",
  "St Mary's Hospital",
  "St Mary's Hospital",
  "St Peter's Hospital",
  "St Richard's Hospital",
  "St Thomas' Hospital",
  "St Vincent's University Hospital",
  "St Woolos Hospital",
  "Stepping Hill Hospital",
  "Stirling Royal Infirmary",
  "Stoke Mandeville Hospital",
  "Stonehaven Medical Practice",
  "Sunderland Royal Infirmary",
  "Sussex Community Dermatology Service",
  "Swansea University",
  "Tallaght Hospital",
  "Tameside General Hospital",
  "Temple Street Children's University Hospital",
  "The Alfred Hospital",
  "The Ardbryan Clinic",
  "The Charles Institute of Dermatology",
  "The Christie NHS Foundation Trust",
  "The Cranley Clinic",
  "The Face and Eye Clinic",
  "The Great Western Hospital",
  "The Health Centre",
  "The Homerton Hospital",
  "The Institute of Dermato-immun",
  "The James Cook University Hospital",
  "The Kennedy Institute of Rheumatology",
  "The London Clinic",
  "The New Queen Elizabeth Hospital Birmingham",
  "The Queen Elizabeth Hospital King's Lynn Trust",
  "The Quintins Medical Centre",
  "The Rejuvenation Clinic",
  "The Royal Oldham Hospital",
  "The Sefton Suite",
  "The Ulster Independent Clinic",
  "The University of British Columbia",
  "The University of Cambridge School of Clinical Medicine",
  "The University Of Manchester",
  "The University of Sheffield",
  "The Village Surgery",
  "The Winnipeg Clinic",
  "Thomson GM & Partners",
  "Tisch Hospital",
  "Tokyo Teishin Hospital",
  "Torbay Hospital",
  "Trafford General Hospital",
  "Trincay Medical Services",
  "Tunbridge Wells Hospital",
  "UCL Institute of Child Health",
  "Ulster Hospital",
  "Unit 14 Belevedere Court",
  "Univ of Michigan Sch Med",
  "Universita Degli Studi Di Firenze",
  "Universitats Hautklinik",
  "Universitatsklinik fur Dermatologie",
  "Universitatsklinikum Carl Gustav Carus",
  "Universite Catholique de Louvain",
  "University Children's Hospital",
  "University College Dublin",
  "University College London Hospital",
  "University College London Medical School",
  "University Hospital Coventry",
  "University Hospital Crete",
  "University Hospital Galway",
  "University Hospital Limerick",
  "University Hospital Llandough",
  "University Hospital of North Durham",
  "University Hospital Of North Staffordshi",
  "University Hospital of Wales",
  "University Hospital 'Sestre Milosrdnice'",
  "University Hospital Waterford",
  "University Hospitals Birmingham NHS Foundation Trust",
  "University of Birmingham Medical School",
  "University of Bradford",
  "University of Bristol Medical School",
  "University Of British Columbia",
  "University of California",
  "University of Colorado Hospital",
  "University of Connecticut Health Center",
  "University of Dundee",
  "University of Durham",
  "University of East Anglia",
  "University of Edinburgh",
  "University of Exeter",
  "University of Florence",
  "University of Glasgow",
  "University of Graz",
  "University of Hong Kong",
  "University Of Leeds",
  "University of Leicester",
  "University of Leipzig",
  "University of Lund",
  "University of Manchester Medical School",
  "University of Newcastle Medical School",
  "University of Nijmegen",
  "University of Nottingham",
  "University of Sheffield",
  "University Of Southampton",
  "University of Texas - Houston",
  "University of Ulster",
  "University of Vienna",
  "Vancouver General Hospital",
  "Vernova Healthcare Community Interest Company",
  "Victoria Hospital",
  "Virgin Care East Riding LLP",
  "Vrije Universtiteit",
  "Waikato Hospital",
  "Walsall Hospital",
  "Warwick Hospital",
  "Watford General Hospital",
  "Weatherall Institute Of Molecular Medici",
  "Wessex Skin Clinic",
  "West Middlesex University Hospital",
  "West Suffolk Hospital",
  "West Wales General Hospital",
  "Western General Hospital",
  "Western Infirmary",
  "Weston General Hospital",
  "Wexham Park Hospital",
  "Whipps Cross Hospital",
  "Whiston Hospital",
  "Whiteabbey Hospital",
  "Whittington Hospital",
  "William Harvey Hospital",
  "Withington Hospital",
  "Withybush Hospital",
  "Women's College Hospital",
  "Woodbridge Hill Surgery",
  "Worcestershire Royal Hospital",
  "Worthing Hospital",
  "Wrexham Maelor Hospital",
  "Wroclaw Medical University",
  "Wycombe General Hospital",
  "Wythenshawe Hospital",
  "Yeovil District Hospital",
  "York Hospital",
  "Ysbyty Gwynedd Hospital",
];

export const ETHNIC_GROUPES = [
  "Asian or Asian British: Indian",
  "Asian or Asian British: Pakistani",
  "Asian or Asian British: Bangladeshi",
  "Asian or Asian British: Chinese",
  "Any other Asian background",
  "Black, Black British, Caribbean or African: Caribbean",
  "Black, Black British, Caribbean or African: African background",
  "Any other Black, Black British or Caribbean background",
  "Mixed or Multiple ethnic groups: White and Black Caribbean",
  "Mixed or Multiple ethnic groups: White and Black African",
  "Mixed or Multiple ethnic groups: White and Asian",
  "Any other Mixed or Multiple background",
  "White: English, Welsh, Scottish, Northern Irish or British",
  "White: Irish",
  "White: Gypsy or Irish Traveller",
  "White: Roma",
  "Any other white background",
  "Other ethnic group: Arab",
  "Any other ethnic group",
  "Prefer Not To Say",
];
