// ⬇️ refactor all pick lists point form
// {{host}}/catalogue/fields/core_membershipapplication

export const DATA = [
  {
    id: 1,
    imgUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2018/11/Skin-cancer-press-release-28-11-18-cropped.jpg",
    title:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    theme: "blue",
    url: "/go-to-url",
    name: "Dr Tanya Bleiker",
    about:
      "President in The Chair July 2020 - July 2022 University Hospitals of Derby and Burton",
    profileUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2018/12/Image_62_Text__Image.jpg",
  },
  {
    id: 2,
    imgUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2021/04/Copy-of-SAW-1-Twitter.png",
    title:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    theme: "yellow",
    url: "/go-to-url",
    name: "Dr Mabs Chowdhury",
    about:
      "President in The Chair July 2020 - July 2022 University Hospitals of Derby and Burton",
    profileUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2018/12/Image_62_Text__Image.jpg",
    cardTitle: "This is a tile",
  },
  {
    id: 3,
    imgUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2020/12/pexels-polina-tankilevitch-3735747-scaled-e1607434622754.jpg",
    title:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    theme: "danger",
    url: "/go-to-url",
    name: "Professor Richard Warren",
    about:
      "President in The Chair July 2020 - July 2022 University Hospitals of Derby and Burton",
    profileUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2018/12/Image_62_Text__Image.jpg",
    cardTitle: "This is a tile",
  },
  {
    id: 4,
    imgUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2020/12/pexels-polina-tankilevitch-3735747-scaled-e1607434622754.jpg",
    title:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    theme: "danger",
    url: "/go-to-url",
    name: "Professor Richard Warren",
    about:
      "President in The Chair July 2020 - July 2022 University Hospitals of Derby and Burton",
    profileUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2018/12/Image_62_Text__Image.jpg",
    cardTitle: "This is a tile",
  },
];

export const MENU_DATA = [
  {
    title: "Patient Information Leaflets",
    url: "/patient-information-leaflets/",
  },
  {
    title: "Clinical Guidelines",
    url: "/guidelines-and-standards/clinical-guidelines/",
  },
  {
    title: "Dermatology Groups and Charities",
    url: "/derm-groups-charity/",
  },
  {
    title: "Patient Hub",
    url: "https://www.skinhealthinfo.org.uk/",
  },
  {
    title: "COVID 19 Information",
    url: "/covid-19/",
  },
  {
    title: "BJD Journal",
    // url: "https://academic.oup.com/bjd",
    url:
      "https://skylarkdev.digital/httplogger" +
      encodeURI(
        "?origurl=https://academic.oup.com/bjd?sigmaHost=academic.oup.com"
      ),
  },
  {
    title: "CED Journal",
    url:
      "https://academic.oup.com/ced" +
      encodeURI(
        "?origurl=https://academic.oup.com/ced?sigmaHost=academic.oup.com"
      ),
  },
  {
    title: "SHD Journal",
    url: "https://onlinelibrary.wiley.com/journal/2690442x?gclid=Cj0KCQiAu62QBhC7ARIsALXijXT-nKH8mRIKSZ4IT5dxjWslV4XzyQAxYppPvYNY4K-b9GR6IDtR7X0aAq8hEALw_wcB",
  },
  {
    title: "BAD Video Library",
    url: "/videos/",
  },
  {
    title: "PushFar Mentoring platform",
    url: "https://www.pushfar.com/employee-register/VYhR5MtTPX/",
  },
  {
    title: "Dermatology Referral Guidelines",
    url: "/referrals/",
  },
  // 📌 uncomment to enable FAD on quick links
  // {
  //   title: "FAD",
  //   url: "/find-a-dermatologist/",
  // },
];

export const ALPHABET = [
  "0-9",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];

export const UK_COUNTIES = [
  "Avon",
  "Bedfordshire",
  "Berkshire",
  "Buckinghamshire",
  "Cambridgeshire",
  "Cheshire",
  "Cleveland",
  "Cornwall",
  "Cumbria",
  "Derbyshire",
  "Devon",
  "Dorset",
  "Durham",
  "East Sussex",
  "Essex",
  "Gloucestershire",
  "Hampshire",
  "Herefordshire",
  "Hertfordshire",
  "Isle of Wight",
  "Kent",
  "Lancashire",
  "Leicestershire",
  "Lincolnshire",
  "London",
  "Merseyside",
  "Middlesex",
  "Norfolk",
  "Northamptonshire",
  "Northumberland",
  "North Humberside",
  "North Yorkshire",
  "Nottinghamshire",
  "Oxfordshire",
  "Rutland",
  "Shropshire",
  "Somerset",
  "South Humberside",
  "South Yorkshire",
  "Staffordshire",
  "Suffolk",
  "Surrey",
  "Tyne and Wear",
  "Warwickshire",
  "West Midlands",
  "West Sussex",
  "West Yorkshire",
  "Wiltshire",
  "Worcestershire",
  "Clwyd",
  "Dyfed",
  "Gwent",
  "Gwynedd",
  "Mid Glamorgan",
  "Powys",
  "South Glamorgan",
  "West Glamorgan",
  "Aberdeenshire",
  "Angus",
  "Argyll",
  "Ayrshire",
  "Banffshire",
  "Berwickshire",
  "Bute",
  "Caithness",
  "Clackmannanshire",
  "Dumfriesshire",
  "Dunbartonshire",
  "East Lothian",
  "Fife",
  "Inverness-shire",
  "Kincardineshire",
  "Kinross-shire",
  "Kirkcudbrightshire",
  "Lanarkshire",
  "Midlothian",
  "Moray",
  "Nairnshire",
  "Orkney",
  "Peeblesshire",
  "Perthshire",
  "Renfrewshire",
  "Ross-shire",
  "Roxburghshire",
  "Selkirkshire",
  "Shetland",
  "Stirlingshire",
  "Sutherland",
  "West Lothian",
  "Wigtownshire",
  "Antrim",
  "Armagh",
  "Down",
  "Fermanagh",
  "Londonderry",
  "Tyrone",
];

export const UK_COUNTRIES = [
  "England",
  "Wales",
  "Scotland",
  "Northern Ireland",
];

export const UK_HOSPITALS = [
  {
    name: "Royal Bournemouth Hospital",
    address1_composite: "Castle Lane East\r\nBournemouth BH7 7DW",
    customertypecode: "Hospital",
    address1_line1: "Castle Lane East",
    accountid: "74b0088a-edd1-e811-a966-000d3a3911fb",
    address1_city: "Bournemouth",
    address1_postalcode: "BH7 7DW",
  },
  {
    name: "King's College Hospital - Beckenham Beacon",
    address1_composite:
      "Beckenham Beacon\r\n379 Croydon Road\r\nBeckenham\r\nBR3 3QL\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Beckenham Beacon",
    accountid: "1ab77d1c-7828-e911-a96f-000d3a3911fb",
    address1_city: "Beckenham",
    address1_postalcode: "BR3 3QL",
  },
  {
    name: "Dermatology Clinic",
    address1_composite:
      "The Dermatology Clinic\r\nUptown Mirdif\r\nDubai PO Box 232328\r\nUnited Arab Emirates",
    customertypecode: "Hospital",
    address1_line1: "The Dermatology Clinic",
    accountid: "bcc718af-74e6-e811-a96a-000d3a391893",
    address1_city: "Dubai",
    address1_postalcode: "PO Box 232328",
  },
  {
    name: "Bupa Health and Dental Care- Solihull",
    address1_composite:
      "Bupa Health & Dental Care\r\n47 Station Road\r\nSolihull\r\nWest Midlands\r\nB91 3RT\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Bupa Health & Dental Care",
    accountid: "2112162c-76e6-e811-a96a-000d3a391893",
    address1_city: "Solihull",
    address1_postalcode: "B91 3RT",
  },
  {
    name: "İskenderun Gelişim Hospital-Department of Dermatology",
    address1_composite:
      "İskenderun Gelişim Hospital\r\nİskenderun\r\nHatay\r\n31200\r\nTurkey",
    customertypecode: "Hospital",
    address1_line1: "İskenderun Gelişim Hospital",
    accountid: "e06260ea-7be6-e811-a96a-000d3a391893",
    address1_city: null,
    address1_postalcode: "31200",
  },
  {
    name: "Belgravia Dermatology Limited",
    address1_composite:
      "Belgravia Dermatology Ltd\r\n6 Ludgate Square\r\nLondon\r\nEC4M 7AS\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Belgravia Dermatology Ltd",
    accountid: "3776c0ac-2ca1-e811-a95d-000d3a391928",
    address1_city: "London",
    address1_postalcode: "EC4M 7AS",
  },
  {
    name: "Eudelo Dermatology & Skin Wellbeing",
    address1_composite:
      "Eudelo\r\n63 Bondway\r\nLondon\r\nSW8 1SJ\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Eudelo",
    accountid: "72034f77-2a81-e911-a975-000d3a391928",
    address1_city: "London",
    address1_postalcode: "SW8 1SJ",
  },
  {
    name: "The Charles Institute of Dermatology",
    address1_composite:
      "The Charles Institute of Dermatology\r\nUniversity College Dublin\r\nBelfield\r\nDublin 4\r\nIreland",
    customertypecode: "Hospital",
    address1_line1: "The Charles Institute of Dermatology",
    accountid: "40972edc-a7c0-e811-a964-000d3a391a6a",
    address1_city: "Dublin 4",
    address1_postalcode: null,
  },
  {
    name: "The Face and Eye Clinic",
    address1_composite:
      "The Face and Eye Clinic\r\n2 Gibwood Road\r\nManchester\r\nGreater Manchester\r\nM22 4BT\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "The Face and Eye Clinic",
    accountid: "8bf95570-f213-e911-a96e-000d3a391a6a",
    address1_city: "Manchester",
    address1_postalcode: "M22 4BT",
  },
  {
    name: "Portuguese Institute of Oncology",
    address1_composite:
      "Portuguese Institute of Oncology\r\nLima Basto\r\nLisbon\r\nPortugal",
    customertypecode: "Hospital",
    address1_line1: "Portuguese Institute of Oncology",
    accountid: "2f5115ef-e74e-e911-a972-000d3a391a6a",
    address1_city: "Lisbon",
    address1_postalcode: null,
  },
  {
    name: "Bayside Dermatology",
    address1_composite: "111 Halifax St\r\nBrighton VIC 3186\r\nAustralia",
    customertypecode: "Hospital",
    address1_line1: "111 Halifax St",
    accountid: "11162c76-be77-e911-a973-000d3a391cda",
    address1_city: "Brighton",
    address1_postalcode: "3186",
  },
  {
    name: "The Ardbryan Clinic",
    address1_composite:
      "The Ardbryan Clinic\r\n1 Dublin Road\r\nBryanstown\r\nDrogheda A92\r\nCounty Louth\r\nIreland",
    customertypecode: "Hospital",
    address1_line1: "The Ardbryan Clinic",
    accountid: "ef4d5088-70e2-e811-a968-000d3a391e8e",
    address1_city: "Drogheda",
    address1_postalcode: "A92",
  },
  {
    name: "Harefield Hospital",
    address1_composite:
      "Harefield Hospital\r\nHill End Road\r\nHarefield\r\nUxbridge\r\nUB9 6JH\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Harefield Hospital",
    accountid: "8c3c649b-72e2-e811-a968-000d3a391e8e",
    address1_city: "Uxbridge",
    address1_postalcode: "UB9 6JH",
  },
  {
    name: "About Health Community Dermatology Service",
    address1_composite:
      "The Innovation Centre\r\n1 Evolution Park\r\nHaslingden Road\r\nBlackburn\r\nLancashire\r\nBB1 2FD\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "The Innovation Centre",
    accountid: "766c0e82-37e3-e811-a968-000d3a391e8e",
    address1_city: "Blackburn",
    address1_postalcode: "BB1 2FD",
  },
  {
    name: "Iwade Health Centre",
    address1_composite:
      "1 Monins Road\r\nIwade\r\nSittingbourne\r\nKent\r\nME9 8TY\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "1 Monins Road",
    accountid: "457566bc-38e3-e811-a968-000d3a391e8e",
    address1_city: "Sittingbourne",
    address1_postalcode: "ME9 8TY",
  },
  {
    name: "The Sefton Suite",
    address1_composite:
      "The Sefton Suite\r\n1 Kenilworth Road\r\nCrosby\r\nLiverpool\r\nMerseyside\r\nL23 3AD\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "The Sefton Suite",
    accountid: "ac0b4927-3be3-e811-a968-000d3a391e8e",
    address1_city: "Liverpool",
    address1_postalcode: "L23 3AD",
  },
  {
    name: "Women's College Hospital",
    address1_composite: "76 Grenville St\r\nToronto ON M5S 1B2\r\nCanada",
    customertypecode: "Hospital",
    address1_line1: "76 Grenville St",
    accountid: "22ec4c13-20ad-e911-a976-000d3a391e8e",
    address1_city: "Toronto",
    address1_postalcode: "M5S 1B2",
  },
  {
    name: "Chelsfield Park Hospital",
    address1_composite:
      "Chelfield Park Hopsital\r\nChelsfield\r\nKent\r\nBR6 7RG\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Chelfield Park Hopsital",
    accountid: "a03ed428-a00b-ea11-a811-000d3a4a17c4",
    address1_city: null,
    address1_postalcode: "BR6 7RG",
  },
  {
    name: "Not Listed",
    address1_composite: null,
    customertypecode: "Hospital",
    address1_line1: null,
    accountid: "439b5c62-4747-ea11-a812-000d3a4a17c4",
    address1_city: null,
    address1_postalcode: null,
  },
  {
    name: "Unit 14 Belevedere Court",
    address1_composite: "2 Sandford Road\r\nSt Lucia Qld\r\n4067\r\nAustralia",
    customertypecode: "Hospital",
    address1_line1: "2 Sandford Road",
    accountid: "44690bde-87fe-e611-80df-1458d0432720",
    address1_city: null,
    address1_postalcode: "4067",
  },
  {
    name: "Universita Degli Studi Di Firenze",
    address1_composite:
      "Istituto Di Clinica Dermosifilopatica\r\n50121 Firenze\r\nVia Degli Alfani 37\r\n. Florence\r\nItaly",
    customertypecode: "Hospital",
    address1_line1: "Istituto Di Clinica Dermosifilopatica",
    accountid: "4c690bde-87fe-e611-80df-1458d0432720",
    address1_city: "Florence",
    address1_postalcode: ".",
  },
  {
    name: "Universitatsklinik fur Dermatologie",
    address1_composite:
      "und Venerologie\r\nAuenbruggerplatz 8\r\nLandeskrankenhaus\r\nA-8036 Graz\r\nAustria",
    customertypecode: "Hospital",
    address1_line1: "und Venerologie",
    accountid: "70b4a97a-88fe-e611-80df-1458d0432720",
    address1_city: "Graz",
    address1_postalcode: "A-8036",
  },
  {
    name: "Victoria Hospital",
    address1_composite:
      "Hayfield Road\r\nKirkcaldy\r\nFife KY2 5AH\r\nScotland",
    customertypecode: "Hospital",
    address1_line1: "Hayfield Road",
    accountid: "cbe2dd86-88fe-e611-80df-1458d0432720",
    address1_city: "Fife",
    address1_postalcode: "KY2 5AH",
  },
  {
    name: "Bunny Hill Primary Care Centre",
    address1_composite:
      "Hylton Lane\r\nSunderland\r\nTyne & Wear\r\nSR5 4BW\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Hylton Lane",
    accountid: "a62b15e2-f803-e711-80e0-1458d0432720",
    address1_city: "Sunderland",
    address1_postalcode: "SR5 4BW",
  },
  {
    name: "Stoke Mandeville Hospital",
    address1_composite:
      "Mandeville Road\r\nAylesbury\r\nBucks\r\nHP21 8AL\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Mandeville Road",
    accountid: "e27315ea-f903-e711-80e0-1458d0432720",
    address1_city: "Aylesbury",
    address1_postalcode: "HP21 8AL",
  },
  {
    name: "University of Colorado Hospital",
    address1_composite:
      "PO Box 6511\r\nMail Stop B-216\r\nAurora\r\nCO 80045\r\nUnited States",
    customertypecode: "Hospital",
    address1_line1: "PO Box 6511",
    accountid: "8d076e81-9e73-e711-80ee-1458d0432720",
    address1_city: null,
    address1_postalcode: "CO 80045",
  },
  {
    name: "Bristol Royal Infirmary",
    address1_composite:
      "University Hospital Bristol\r\nBristol Royal Infirmary\r\nMarlborough Street\r\nBristol\r\nSomerset\r\nBS2 8HW\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "University Hospital Bristol",
    accountid: "353d0f68-2ede-e611-80da-3863bb344ac8",
    address1_city: "Bristol",
    address1_postalcode: "BS2 8HW",
  },
  {
    name: "Derriford Hospital",
    address1_composite:
      "Derriford Road\r\nDerriford\r\nPlymouth\r\nDevon\r\nPL6 8DH\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Derriford Road",
    accountid: "373d0f68-2ede-e611-80da-3863bb344ac8",
    address1_city: "Plymouth",
    address1_postalcode: "PL6 8DH",
  },
  {
    name: "Gloucestershire Royal Hospital",
    address1_composite:
      "Great Western Road\r\nGloucester\r\nGL1 3NN\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Great Western Road",
    accountid: "393d0f68-2ede-e611-80da-3863bb344ac8",
    address1_city: "Gloucester",
    address1_postalcode: "GL1 3NN",
  },
  {
    name: "Musgrove Park Hospital",
    address1_composite: ".\r\nTaunton\r\nSomerset\r\nTA1 5DA\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: ".",
    accountid: "3b3d0f68-2ede-e611-80da-3863bb344ac8",
    address1_city: "Taunton",
    address1_postalcode: "TA1 5DA",
  },
  {
    name: "North Devon District Hospital",
    address1_composite:
      "Raleigh Park\r\nBarnstaple\r\nDevon\r\nEX31 4JB\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Raleigh Park",
    accountid: "3d3d0f68-2ede-e611-80da-3863bb344ac8",
    address1_city: "Barnstaple",
    address1_postalcode: "EX31 4JB",
  },
  {
    name: "Princess Elizabeth Hospital",
    address1_composite: "Le Vauquiedor\r\nSt Martins GY4 6UU\r\nGuernsey",
    customertypecode: "Hospital",
    address1_line1: "Le Vauquiedor",
    accountid: "3f3d0f68-2ede-e611-80da-3863bb344ac8",
    address1_city: "St Martins",
    address1_postalcode: "GY4 6UU",
  },
  {
    name: "Royal Cornwall Hospital",
    address1_composite:
      "European Centre for Environment\r\nUniversity of Exeter Medical School\r\nKnowledge Spa\r\nTRURO\r\nCornwall\r\nTR1 3HD\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "European Centre for Environment",
    accountid: "413d0f68-2ede-e611-80da-3863bb344ac8",
    address1_city: "TRURO",
    address1_postalcode: "TR1 3HD",
  },
  {
    name: "Royal Devon & Exeter Hospital",
    address1_composite:
      "Barrack Road\r\nExeter\r\nDevon\r\nEX2 5DW\r\nUNITED KINGDOM",
    customertypecode: "Hospital",
    address1_line1: "Barrack Road",
    accountid: "433d0f68-2ede-e611-80da-3863bb344ac8",
    address1_city: "Exeter",
    address1_postalcode: "EX2 5DW",
  },
  {
    name: "Royal United Hospital",
    address1_composite:
      "Combe Park\r\nBath\r\nAvon\r\nBA1 3NG\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Combe Park",
    accountid: "453d0f68-2ede-e611-80da-3863bb344ac8",
    address1_city: "Bath",
    address1_postalcode: "BA1 3NG",
  },
  {
    name: "Salisbury District Hospital",
    address1_composite:
      "Odstock\r\nSalisbury\r\nWiltshire\r\nSP2 8BJ\r\nUNITED KINGDOM",
    customertypecode: "Hospital",
    address1_line1: "Odstock",
    accountid: "473d0f68-2ede-e611-80da-3863bb344ac8",
    address1_city: "Salisbury",
    address1_postalcode: "SP2 8BJ",
  },
  {
    name: "Southmead Hospital",
    address1_composite:
      "Southmead Road\r\nWestbury-on-Trym\r\nBristol\r\nBS10 5NB\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Southmead Road",
    accountid: "493d0f68-2ede-e611-80da-3863bb344ac8",
    address1_city: "Bristol",
    address1_postalcode: "BS10 5NB",
  },
  {
    name: "The Great Western Hospital",
    address1_composite:
      "Marlborough Road\r\nSwindon\r\nWiltshire\r\nSN3 6BB\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Marlborough Road",
    accountid: "4b3d0f68-2ede-e611-80da-3863bb344ac8",
    address1_city: "Swindon",
    address1_postalcode: "SN3 6BB",
  },
  {
    name: "Torbay Hospital",
    address1_composite:
      "Lawes Bridge\r\nTorquay\r\nDevon\r\nTQ2 7AA\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Lawes Bridge",
    accountid: "4d3d0f68-2ede-e611-80da-3863bb344ac8",
    address1_city: "Torquay",
    address1_postalcode: "TQ2 7AA",
  },
  {
    name: "Yeovil District Hospital",
    address1_composite:
      "Higher Kingston\r\nYeovil\r\nAvon\r\nBA21 4AT\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Higher Kingston",
    accountid: "4f3d0f68-2ede-e611-80da-3863bb344ac8",
    address1_city: "Yeovil",
    address1_postalcode: "BA21 4AT",
  },
  {
    name: "Brighton & Sussex University Hospitals NHS Trust",
    address1_composite: "UNITED KINGDOM",
    customertypecode: "Hospital",
    address1_line1: null,
    accountid: "4354583a-87fe-e611-80dd-3863bb349b40",
    address1_city: null,
    address1_postalcode: null,
  },
  {
    name: "Dermatology Unit",
    address1_composite: "131 Stow Hill\r\nNewport NP20 4EZ\r\nWales",
    customertypecode: "Hospital",
    address1_line1: "131 Stow Hill",
    accountid: "dfb36340-87fe-e611-80dd-3863bb349b40",
    address1_city: "Newport",
    address1_postalcode: "NP20 4EZ",
  },
  {
    name: "Faculty Hospital Brno",
    address1_composite:
      "Department of Dermatology\r\nPekarska 53\r\nCS-656 91 Brno Dorset \r\nCzech Republic",
    customertypecode: "Hospital",
    address1_line1: "Department of Dermatology",
    accountid: "e5b36340-87fe-e611-80dd-3863bb349b40",
    address1_city: "Brno",
    address1_postalcode: "CS-656 91",
  },
  {
    name: "Glenferrie Dermatology",
    address1_composite: null,
    customertypecode: "Hospital",
    address1_line1: null,
    accountid: "f2b36340-87fe-e611-80dd-3863bb349b40",
    address1_city: null,
    address1_postalcode: null,
  },
  {
    name: "Greater Glasgow and Clyde NHS Board",
    address1_composite:
      "Dalian House\r\nPO Box 15329\r\n350 St Vincent Street\r\nGlasgow\r\nG3 8YZ\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Dalian House",
    accountid: "fbb36340-87fe-e611-80dd-3863bb349b40",
    address1_city: "Glasgow",
    address1_postalcode: "G3 8YZ",
  },
  {
    name: "Heart of England NHS Foundation Trust",
    address1_composite: null,
    customertypecode: "Hospital",
    address1_line1: null,
    accountid: "a9107446-87fe-e611-80dd-3863bb349b40",
    address1_city: null,
    address1_postalcode: null,
  },
  {
    name: "Hospital of Brno-Bohunice",
    address1_composite:
      "2nd Department of Dermatology\r\nJihlavska 100\r\n600 00 Brno-Bohunice\r\nCzech Republic",
    customertypecode: "Hospital",
    address1_line1: "2nd Department of Dermatology",
    accountid: "af107446-87fe-e611-80dd-3863bb349b40",
    address1_city: "Brno-Bohunice",
    address1_postalcode: "600 00",
  },
  {
    name: "Khartouom General Hospital",
    address1_composite: ".\r\nKhartoum .\r\nSudan",
    customertypecode: "Hospital",
    address1_line1: ".",
    accountid: "b7107446-87fe-e611-80dd-3863bb349b40",
    address1_city: "Khartoum",
    address1_postalcode: ".",
  },
  {
    name: "Klinica Dermatologiczna",
    address1_composite: "U1 Kopernika 17\r\n. Krakow\r\nPoland",
    customertypecode: "Hospital",
    address1_line1: "U1 Kopernika 17",
    accountid: "bf107446-87fe-e611-80dd-3863bb349b40",
    address1_city: "Krakow",
    address1_postalcode: ".",
  },
  {
    name: "Ministry of Health",
    address1_composite:
      "Director General of Health Affairs\r\nEastern Province\r\nDammam 31176\r\nSaudi Arabia",
    customertypecode: "Hospital",
    address1_line1: "Director General of Health Affairs",
    accountid: "cd107446-87fe-e611-80dd-3863bb349b40",
    address1_city: "Dammam",
    address1_postalcode: "31176",
  },
  {
    name: "Mu'tah University Karak",
    address1_composite: "PO Box 51\r\nKarak 61710\r\nJordan",
    customertypecode: "Hospital",
    address1_line1: "PO Box 51",
    accountid: "d3107446-87fe-e611-80dd-3863bb349b40",
    address1_city: "Karak",
    address1_postalcode: "61710",
  },
  {
    name: "New Royal Infirmary",
    address1_composite:
      "51 Little France Crescent\r\nEdinburgh\r\nEH16 4SA\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "51 Little France Crescent",
    accountid: "d9107446-87fe-e611-80dd-3863bb349b40",
    address1_city: "Edinburgh",
    address1_postalcode: "EH16 4SA",
  },
  {
    name: "Nr Khalidi Hospital",
    address1_composite:
      "Ben Khaldoun Street\r\nPO Box 5720\r\nAmman .\r\nJordan",
    customertypecode: "Hospital",
    address1_line1: "Ben Khaldoun Street",
    accountid: "e0107446-87fe-e611-80dd-3863bb349b40",
    address1_city: "Amman",
    address1_postalcode: ".",
  },
  {
    name: "Peninsula Medical School",
    address1_composite: null,
    customertypecode: "Hospital",
    address1_line1: null,
    accountid: "e9ee6f90-87fe-e611-80dd-3863bb349b40",
    address1_city: null,
    address1_postalcode: null,
  },
  {
    name: "Princess Royal University Hospital",
    address1_composite:
      "Farnborough Common\r\nORPINGTON\r\nKent\r\nBR6 8ND\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Farnborough Common",
    accountid: "08ef6f90-87fe-e611-80dd-3863bb349b40",
    address1_city: "ORPINGTON",
    address1_postalcode: "BR6 8ND",
  },
  {
    name: "Queen Mary University Of London Blizard Building",
    address1_composite:
      "Blizard Building\r\n4 Newark Street\r\nLondon\r\nE1 2AT\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Blizard Building",
    accountid: "2aef6f90-87fe-e611-80dd-3863bb349b40",
    address1_city: "London",
    address1_postalcode: "E1 2AT",
  },
  {
    name: "Royal North Shore Hospital",
    address1_composite: "Pacific Highway\r\nSt Leonards Nsw 2065\r\nAustralia",
    customertypecode: "Hospital",
    address1_line1: "Pacific Highway",
    accountid: "feb76896-87fe-e611-80dd-3863bb349b40",
    address1_city: "St Leonards",
    address1_postalcode: "2065",
  },
  {
    name: "School of Pharmacy and Biomedical Sciences",
    address1_composite:
      "King Henry I Street\r\nPortsmouth\r\nPO1 2DZ\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "King Henry I Street",
    accountid: "12b86896-87fe-e611-80dd-3863bb349b40",
    address1_city: "Portsmouth",
    address1_postalcode: "PO1 2DZ",
  },
  {
    name: "Service De Dermatologie",
    address1_composite: "CHU Charles Nicolle\r\n76031 Rouen Cedex\r\nFrance",
    customertypecode: "Hospital",
    address1_line1: "CHU Charles Nicolle",
    accountid: "19b86896-87fe-e611-80dd-3863bb349b40",
    address1_city: "Rouen",
    address1_postalcode: "76031",
  },
  {
    name: "Sitaram Bhartia Institute for Science & Research",
    address1_composite:
      "B-16, Mehrauli Institutional Area\r\nNew Delhi 110016\r\nIndia",
    customertypecode: "Hospital",
    address1_line1: "B-16, Mehrauli Institutional Area",
    accountid: "32b86896-87fe-e611-80dd-3863bb349b40",
    address1_city: "New Delhi",
    address1_postalcode: "110016",
  },
  {
    name: "Sunderland Royal Infirmary",
    address1_composite:
      "Kayll Road\r\nSunderland\r\nTyne & Wear\r\nSR4 7PP\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Kayll Road",
    accountid: "96176a35-fa03-e711-80de-3863bb349b40",
    address1_city: "Sunderland",
    address1_postalcode: "SR4 7PP",
  },
  {
    name: "Universite Catholique de Louvain",
    address1_composite:
      "Unite de Dermatologie\r\n30 Clos Chapelle-Aux-Champs\r\nUCL 3033\r\n1200 Brussels\r\nBelgium",
    customertypecode: "Hospital",
    address1_line1: "Unite de Dermatologie",
    accountid: "dc176a35-fa03-e711-80de-3863bb349b40",
    address1_city: "Brussels",
    address1_postalcode: "1200",
  },
  {
    name: "London Dermatology Centre",
    address1_composite:
      "217 Albany Street\r\nLONDON\r\nNW1 4AB\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "217 Albany Street",
    accountid: "c7b04d4d-fa03-e711-80de-3863bb349b40",
    address1_city: "LONDON",
    address1_postalcode: "NW1 4AB",
  },
  {
    name: "Trincay Medical Services",
    address1_composite:
      "Suite 1204\r\nCamana Bay\r\nGRAND CAYMAN KY1-1006\r\nCayman Islands",
    customertypecode: "Hospital",
    address1_line1: "Suite 1204",
    accountid: "ebb04d4d-fa03-e711-80de-3863bb349b40",
    address1_city: "GRAND CAYMAN",
    address1_postalcode: "KY1-1006",
  },
  {
    name: "University Hospitals Bristol Foundation Trust",
    address1_composite:
      "University Hospitals Bristol Foundation Trust\r\nBristol\r\nBS2 8HW\r\nUNITED KINGDOM",
    customertypecode: "Hospital",
    address1_line1: "University Hospitals Bristol Foundation Trust",
    accountid: "921d7736-53f8-e611-80e2-3863bb351f50",
    address1_city: "Bristol",
    address1_postalcode: "BS2 8HW",
  },
  {
    name: "48th Medical Group",
    address1_composite:
      "3 Bridge Court\r\nBridge Road\r\nGrays\r\nEssex\r\nRM17 6BW\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "3 Bridge Court",
    accountid: "1c0b2d47-53f8-e611-80e2-3863bb351f50",
    address1_city: "Grays",
    address1_postalcode: "RM17 6BW",
  },
  {
    name: "9A Wilbraham Place",
    address1_composite: ".\r\nLONDON\r\nSW1X 9AE\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: ".",
    accountid: "a8e12e4d-53f8-e611-80e2-3863bb351f50",
    address1_city: "LONDON",
    address1_postalcode: "SW1X 9AE",
  },
  {
    name: "Aberdeen Royal Infirmary",
    address1_composite: "Foresterhill\r\nAberdeen AB25 2ZN\r\nScotland",
    customertypecode: "Hospital",
    address1_line1: "Foresterhill",
    accountid: "aee12e4d-53f8-e611-80e2-3863bb351f50",
    address1_city: "Aberdeen",
    address1_postalcode: "AB25 2ZN",
  },
  {
    name: "Addenbrooke's Hospital",
    address1_composite:
      "Hills Road\r\nCambridge\r\nCambridgeshire\r\nCB2 0QQ\r\nUNITED KINGDOM",
    customertypecode: "Hospital",
    address1_line1: "Hills Road",
    accountid: "b8e12e4d-53f8-e611-80e2-3863bb351f50",
    address1_city: "Cambridge",
    address1_postalcode: "CB2 0QQ",
  },
  {
    name: "Aintree University Hospital",
    address1_composite:
      "Longmoor Lane\r\nLiverpool\r\nL9 7AL\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Longmoor Lane",
    accountid: "c0e12e4d-53f8-e611-80e2-3863bb351f50",
    address1_city: "Liverpool",
    address1_postalcode: "L9 7AL",
  },
  {
    name: "Alder Hey Childrens Hospital",
    address1_composite: "Eaton Road\r\nLiverpool\r\nL12 2AP\r\nUNITED KINGDOM",
    customertypecode: "Hospital",
    address1_line1: "Eaton Road",
    accountid: "7675ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: "Liverpool",
    address1_postalcode: "L12 2AP",
  },
  {
    name: "Alexandra Hospital",
    address1_composite:
      "Woodrow Drive\r\nCharles Hastings Way\r\nRedditch\r\nWorcs\r\nB98 7UB\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Woodrow Drive",
    accountid: "7c75ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: "Redditch",
    address1_postalcode: "B98 7UB",
  },
  {
    name: "The Alfred Hospital",
    address1_composite:
      "Commercial Road\r\nPrahran\r\nVictoria 3181\r\nAustralia",
    customertypecode: "Hospital",
    address1_line1: "Commercial Road",
    accountid: "8275ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: "Victoria",
    address1_postalcode: "3181",
  },
  {
    name: "All India Institute Of Medical Sciences",
    address1_composite: "Ansari Nagar\r\nNew Delhi 110029\r\nIndia",
    customertypecode: "Hospital",
    address1_line1: "Ansari Nagar",
    accountid: "8875ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: "New Delhi",
    address1_postalcode: "110029",
  },
  {
    name: "Altnagelvin Area Hospital",
    address1_composite:
      "Glenshane Road\r\nLondonderry BT47 6SB\r\nNorthern Ireland",
    customertypecode: "Hospital",
    address1_line1: "Glenshane Road",
    accountid: "8e75ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: "Londonderry",
    address1_postalcode: "BT47 6SB",
  },
  {
    name: "American Hospital Dubai",
    address1_composite:
      "Oud Metha Road\r\n19th Street\r\nPo Box 5566\r\nDUBAI\r\nUnited Arab Emirates",
    customertypecode: "Hospital",
    address1_line1: "Oud Metha Road",
    accountid: "9475ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: "DUBAI",
    address1_postalcode: null,
  },
  {
    name: "Amersham Hospital",
    address1_composite:
      "Whielden Street\r\nMain Drive\r\nQueen Elizabeth Medical Centre\r\nAmersham\r\nBucks\r\nHP7 0JD\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Whielden Street",
    accountid: "9a75ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: "Amersham",
    address1_postalcode: "HP7 0JD",
  },
  {
    name: "Antrim Area Hospital",
    address1_composite:
      "Bush Road\r\nBlackpool Victoria Hospital\r\nWhinney Heys Road\r\nAntrim BT41 2RL\r\nNorthern Ireland",
    customertypecode: "Hospital",
    address1_line1: "Bush Road",
    accountid: "a075ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: "Antrim",
    address1_postalcode: "BT41 2RL",
  },
  {
    name: "Aorangi Consulting Rooms",
    address1_composite:
      "175 Grey Street\r\nMinerva Road\r\nPalmerston North\r\nPalmerston North .\r\nNew Zealand",
    customertypecode: "Hospital",
    address1_line1: "175 Grey Street",
    accountid: "a675ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: "Palmerston North",
    address1_postalcode: ".",
  },
  {
    name: "Arrowe Park Hospital",
    address1_composite:
      "Arrowe Park Road\r\nUpton\r\nWIRRAL\r\nMerseyside \r\nCH49 5PE\r\nUNITED KINGDOM",
    customertypecode: "Hospital",
    address1_line1: "Arrowe Park Road",
    accountid: "ac75ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: "WIRRAL",
    address1_postalcode: "CH49 5PE",
  },
  {
    name: "As'Ad Al-Hamad Dermatology Center",
    address1_composite: "Al-Sabah Hospital\r\nKuwait 13041\r\nKuwait",
    customertypecode: "Hospital",
    address1_line1: "Al-Sabah Hospital",
    accountid: "b275ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: "Kuwait",
    address1_postalcode: "13041",
  },
  {
    name: "Ashford Hospital",
    address1_composite:
      "London Road\r\nAshford\r\nMiddlesex\r\nTW15 3AA\r\nUNITED KINGDOM",
    customertypecode: "Hospital",
    address1_line1: "London Road",
    accountid: "b875ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: "Ashford",
    address1_postalcode: "TW15 3AA",
  },
  {
    name: "Ashtead Hospital",
    address1_composite: "The Warren\r\nASHTEAD\r\nKT21 2SB\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "The Warren",
    accountid: "be75ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: "ASHTEAD",
    address1_postalcode: "KT21 2SB",
  },
  {
    name: "Auckland District Health Board",
    address1_composite:
      "Greenlane Clinical Centre\r\nPrivate Bag 92189\r\nVictoria Street West\r\nAuckland 1142\r\nNew Zealand",
    customertypecode: "Hospital",
    address1_line1: "Greenlane Clinical Centre",
    accountid: "c475ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: null,
    address1_postalcode: "1142",
  },
  {
    name: "Barnet General Hospital",
    address1_composite:
      "Wellhouse Lane\r\nBarnet\r\nHertfordshire\r\nEN5 3DJ\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Wellhouse Lane",
    accountid: "ca75ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: "Barnet",
    address1_postalcode: "EN5 3DJ",
  },
  {
    name: "Barnsley District Gen Hospital",
    address1_composite:
      "Gawber Road\r\nTrust Headquarters\r\nFarnborough Common\r\nBarnsley\r\nSouth Yorkshire\r\nS75 2EP\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Gawber Road",
    accountid: "d175ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: "Barnsley",
    address1_postalcode: "S75 2EP",
  },
  {
    name: "Basildon University Hospital",
    address1_composite:
      "Nethermayne\r\nTrust Headquarters\r\nHaslingden Road \r\nBasildon\r\nEssex\r\nSS16 5NL\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Nethermayne",
    accountid: "de75ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: "Basildon",
    address1_postalcode: "SS16 5NL",
  },
  {
    name: "Basingstoke & North Hampshire Hospital",
    address1_composite: null,
    customertypecode: "Hospital",
    address1_line1: null,
    accountid: "e475ef53-53f8-e611-80e2-3863bb351f50",
    address1_city: null,
    address1_postalcode: null,
  },
  {
    name: "Baylor University Medical Center",
    address1_composite:
      "Psoriasis Center\r\n3900 Junius Street\r\nSuite 145\r\nDallas, Texas 75246\r\nUSA",
    customertypecode: "Hospital",
    address1_line1: "Psoriasis Center",
    accountid: "c944f659-53f8-e611-80e2-3863bb351f50",
    address1_city: "Dallas",
    address1_postalcode: "75246",
  },
  {
    name: "Baylor University Medical Centre",
    address1_composite:
      "Suite 1058\r\n3600 Gaston Avenue\r\nDallas, Texas 75246-1800\r\nUSA",
    customertypecode: "Hospital",
    address1_line1: "Suite 1058",
    accountid: "cf44f659-53f8-e611-80e2-3863bb351f50",
    address1_city: "Dallas",
    address1_postalcode: "75246-1800",
  },
  {
    name: "Beacon Consultants Clinic",
    address1_composite: "Suite 27\r\nSandyford\r\nDUBLIN 18\r\nIreland",
    customertypecode: "Hospital",
    address1_line1: "Suite 27",
    accountid: "d544f659-53f8-e611-80e2-3863bb351f50",
    address1_city: "DUBLIN",
    address1_postalcode: "18",
  },
  {
    name: "Beaumont Hospital",
    address1_composite: "Beaumont\r\nDublin 9\r\nIreland",
    customertypecode: "Hospital",
    address1_line1: "Beaumont",
    accountid: "db44f659-53f8-e611-80e2-3863bb351f50",
    address1_city: "Dublin",
    address1_postalcode: "9",
  },
  {
    name: "Beckenham Beacon Hospital",
    address1_composite:
      "Beckenham Beacon\r\n379 Croydon Road\r\nBeckenham\r\nBR3 3QL\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Beckenham Beacon",
    accountid: "e144f659-53f8-e611-80e2-3863bb351f50",
    address1_city: "Beckenham",
    address1_postalcode: "BR3 3QL",
  },
  {
    name: "Bedford Hospital",
    address1_composite:
      "Kempston Road\r\nHeath Park\r\nBedford\r\nMK42 9DJ\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Kempston Road",
    accountid: "e744f659-53f8-e611-80e2-3863bb351f50",
    address1_city: "Bedford",
    address1_postalcode: "MK42 9DJ",
  },
  {
    name: "Belfast City Hospital",
    address1_composite: "Lisburn Road\r\nBelfast BT9 7AB\r\nNorthern Ireland",
    customertypecode: "Hospital",
    address1_line1: "Lisburn Road",
    accountid: "f344f659-53f8-e611-80e2-3863bb351f50",
    address1_city: "Belfast",
    address1_postalcode: "BT9 7AB",
  },
  {
    name: "Birmingham Children's Hospital",
    address1_composite:
      "Steelhouse Lane\r\nBirmingham\r\nWest Midlands\r\nB4 6NL\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Steelhouse Lane",
    accountid: "f944f659-53f8-e611-80e2-3863bb351f50",
    address1_city: "Birmingham",
    address1_postalcode: "B4 6NL",
  },
  {
    name: "Birmingham City Hospital",
    address1_composite:
      "Dudley Road\r\nBirmingham\r\nWest Midlands\r\nB18 7QH\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Dudley Road",
    accountid: "ff44f659-53f8-e611-80e2-3863bb351f50",
    address1_city: "Birmingham",
    address1_postalcode: "B18 7QH",
  },
  {
    name: "Blackrock Clinic",
    address1_composite: "Rock Road\r\nBLACKROCK .\r\nCo. Dublin\r\nIreland",
    customertypecode: "Hospital",
    address1_line1: "Rock Road",
    accountid: "0545f659-53f8-e611-80e2-3863bb351f50",
    address1_city: "BLACKROCK",
    address1_postalcode: ".",
  },
  {
    name: "BMI Carrick Glen Hospital",
    address1_composite:
      "Dalmellington Road\r\nAYR\r\nKA6 6PG\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Dalmellington Road",
    accountid: "0b45f659-53f8-e611-80e2-3863bb351f50",
    address1_city: "AYR",
    address1_postalcode: "KA6 6PG",
  },
  {
    name: "BMI The Chaucer Hospital",
    address1_composite:
      "Nackington Road\r\nCANTERBURY\r\nSurrey\r\nCT4 7AR\r\nUnited Kingdom",
    customertypecode: "Hospital",
    address1_line1: "Nackington Road",
    accountid: "1145f659-53f8-e611-80e2-3863bb351f50",
    address1_city: "CANTERBURY",
    address1_postalcode: "CT4 7AR",
  },
];

export const ETHNIC_GROUPS = [
  {
    value: 810170011,
    Label: "African Background",
  },
  {
    value: 810170012,
    Label: "Arab",
  },
  {
    value: 810170008,
    Label: "Bangladeshi",
  },
  {
    value: 810170010,
    Label: "Caribbean",
  },
  {
    value: 810170009,
    Label: "Chinese",
  },
  {
    value: 810170002,
    Label: "Gypsy or Irish Traveller",
  },
  {
    value: 810170006,
    Label: "Indian",
  },
  {
    value: 810170001,
    Label: "Irish",
  },
  {
    value: 810170007,
    Label: "Pakistan",
  },
  {
    value: 215500000,
    Label: "White",
  },
  {
    value: 810170005,
    Label: "- White and Asian",
  },
  {
    value: 810170004,
    Label: "White and Black African",
  },
  {
    value: 810170003,
    Label: "White and Black Caribbean",
  },
  {
    value: 810170000,
    Label: "White British",
  },
  {
    value: 810170013,
    Label: "Other",
  },
];

export const GENDER_GROUPS = [
  {
    value: 215500000,
    Label: "Male",
  },
  {
    value: 215500001,
    Label: "Female",
  },
  {
    value: 215500003,
    Label: "Transgender Female",
  },
  {
    value: 215500004,
    Label: "Transgender Male",
  },
  {
    value: 215500005,
    Label: "Gender Variant/Non-Conforming",
  },
  {
    value: 215500006,
    Label: "Not Listed",
  },
  {
    value: 215500007,
    Label: "Prefer Not to Answer",
  },
  {
    value: 215500002,
    Label: "Unknown",
  },
];

export const sigAppFileds = [
  "py3_title",
  "py3_firstname",
  "py3_lastname",
  "py3_gender",
  "py3_dateofbirth",
  "py3_email",
  "py3_mobilephone",
  "py3_address1ine1",
  "py3_addressline2",
  "py3_addresstowncity",
  "py3_addresszippostalcode",
  "py3_addresscountystate",
  "py3_addresscountry",
  "py3_gmcnumber",
  "bad_currentpost",
  "py3_hospitalid",
  "bad_newhospitaladded",
  "sky_newhospitalname",
  "bad_proposer1",
  "bad_proposer2",
  "py3_ntnno",
  "sky_cvurl",
  "bad_readpolicydocument",
  "sig_readpolicydocument_url_email",
  "py3_currentgrade",
  "bad_qualifications",
  "bad_hasmedicallicence",
  "bad_isbadmember",
  "py3_whatukbasedroleareyou",
  "py3_speciality",
  "bad_interestinfieldquestion",
  "bad_otherjointclinics",
  "bad_mainareaofinterest",
  "bad_includeinthebssciiemaildiscussionforum",
  "py3_insertnhsnetemailaddress",
];

export const prefMailingOption = [
  {
    value: 810170000,
    Label: "Main Hospital",
  },
  {
    value: 810170001,
    Label: "Home",
  },
  // 📌 uncomment if you want to add a new option
  //   value: 810170002,
  //   Label: "Private Practice",
  // },
];

export const proAppFileds = [
  "py3_gmcnumber",
  "py3_otherregulatorybodyreference",
  "py3_ntnno",
  "bad_currentpost",
  "py3_hospitalid",
  "bad_proposer1",
  "bad_proposer2",
  "bad_mrpcqualified",
  "sky_cvurl",
  "py3_currentgrade",
  "sky_newhospitalname",
  "bad_newhospitaladded",
  "bad_expectedyearofqualification",
  "sky_newhospitaltype",
  "bad_memberdirectory",
];
