export const DATA = [
  {
    id: 1,
    imgUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2018/11/Skin-cancer-press-release-28-11-18-cropped.jpg",
    title:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    theme: "blue",
    url: "/go-to-url",
    name: "Dr Tanya Bleiker",
    about:
      "President in The Chair July 2020 - July 2022 University Hospitals of Derby and Burton",
    profileUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2018/12/Image_62_Text__Image.jpg",
  },
  {
    id: 2,
    imgUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2021/04/Copy-of-SAW-1-Twitter.png",
    title:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    theme: "yellow",
    url: "/go-to-url",
    name: "Dr Mabs Chowdhury",
    about:
      "President in The Chair July 2020 - July 2022 University Hospitals of Derby and Burton",
    profileUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2018/12/Image_62_Text__Image.jpg",
    cardTitle: "This is a tile",
  },
  {
    id: 3,
    imgUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2020/12/pexels-polina-tankilevitch-3735747-scaled-e1607434622754.jpg",
    title:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    theme: "danger",
    url: "/go-to-url",
    name: "Professor Richard Warren",
    about:
      "President in The Chair July 2020 - July 2022 University Hospitals of Derby and Burton",
    profileUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2018/12/Image_62_Text__Image.jpg",
    cardTitle: "This is a tile",
  },
  {
    id: 4,
    imgUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2020/12/pexels-polina-tankilevitch-3735747-scaled-e1607434622754.jpg",
    title:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it",
    body: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    theme: "danger",
    url: "/go-to-url",
    name: "Professor Richard Warren",
    about:
      "President in The Chair July 2020 - July 2022 University Hospitals of Derby and Burton",
    profileUrl:
      "https://www.skinhealthinfo.org.uk/wp-content/uploads/2018/12/Image_62_Text__Image.jpg",
    cardTitle: "This is a tile",
  },
];

export const MENU_DATA = [
  {
    title: "Patient Information Leaflets",
    url: "/patient-information-leaflets/",
  },
  {
    title: "BAD Affiliated Groups",
    url: "/derm-groups-charity/",
  },
  {
    title: "Patient Hub",
    url: "https://www.skinhealthinfo.org.uk/",
  },
  {
    title: "COVID 19 Information",
    url: "/covid-19/",
  },
  {
    title: "CED Journal",
    url: "/research-journals/journals/clinical-and-experimental-dermatology/",
  },
  {
    title: "BJD Journal",
    url: "/research-journals/journals/british-journal-of-dermatology/",
  },
  {
    title: "SHD Journal",
    url: " /research-journals/journals/skin-health-and-disease/",
  },
  {
    title: "Clinical Guidelines",
    url: "/guidelines-and-standards/clinical-guidelines/",
  },
];

export const ALPHABET = [
  "0-9",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];

export const UK_COUNTIES = [
  "Avon",
  "Bedfordshire",
  "Berkshire",
  "Buckinghamshire",
  "Cambridgeshire",
  "Cheshire",
  "Cleveland",
  "Cornwall",
  "Cumbria",
  "Derbyshire",
  "Devon",
  "Dorset",
  "Durham",
  "East Sussex",
  "Essex",
  "Gloucestershire",
  "Hampshire",
  "Herefordshire",
  "Hertfordshire",
  "Isle of Wight",
  "Kent",
  "Lancashire",
  "Leicestershire",
  "Lincolnshire",
  "London",
  "Merseyside",
  "Middlesex",
  "Norfolk",
  "Northamptonshire",
  "Northumberland",
  "North Humberside",
  "North Yorkshire",
  "Nottinghamshire",
  "Oxfordshire",
  "Rutland",
  "Shropshire",
  "Somerset",
  "South Humberside",
  "South Yorkshire",
  "Staffordshire",
  "Suffolk",
  "Surrey",
  "Tyne and Wear",
  "Warwickshire",
  "West Midlands",
  "West Sussex",
  "West Yorkshire",
  "Wiltshire",
  "Worcestershire",
  "Clwyd",
  "Dyfed",
  "Gwent",
  "Gwynedd",
  "Mid Glamorgan",
  "Powys",
  "South Glamorgan",
  "West Glamorgan",
  "Aberdeenshire",
  "Angus",
  "Argyll",
  "Ayrshire",
  "Banffshire",
  "Berwickshire",
  "Bute",
  "Caithness",
  "Clackmannanshire",
  "Dumfriesshire",
  "Dunbartonshire",
  "East Lothian",
  "Fife",
  "Inverness-shire",
  "Kincardineshire",
  "Kinross-shire",
  "Kirkcudbrightshire",
  "Lanarkshire",
  "Midlothian",
  "Moray",
  "Nairnshire",
  "Orkney",
  "Peeblesshire",
  "Perthshire",
  "Renfrewshire",
  "Ross-shire",
  "Roxburghshire",
  "Selkirkshire",
  "Shetland",
  "Stirlingshire",
  "Sutherland",
  "West Lothian",
  "Wigtownshire",
  "Antrim",
  "Armagh",
  "Down",
  "Fermanagh",
  "Londonderry",
  "Tyrone",
];

export const UK_COUNTRIES = [
  "England",
  "Wales",
  "Scotland",
  "Northern Ireland",
];
